# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4a43b05e819c57a1d81ff9ee8ffd43257f3e3a4036588a28ab29cf8b9fce06e06d265d86d26982875f33c95f2eef8342238035ee3cda25f4e470d611e3024447

test:
  secret_key_base: 1a200f42a00ea051f874449ed45dad53998cd4f47d71440dda219eec4560aae71eec16cad532d7afc1c9b12d91ef31107414c26eb2bbdc6e99cf37037985c66b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
